### ISSUE TITLE
Uncaught TypeError: serie.group.clip is not a function

### ISSUE THREAD

**Issue by jeremypitten** [blacklabel/custom_events#22]
Using version 1.1.0 and rendering a pie chart I'm seeing the above error thrown from line 31 (or line 76 on a redraw)

I don't understand the logic but the problem is caused by the customEvent.add method setting a boolean true for each event property on the serie.group element, which blocks the serie.group.prototype.clip function from being invoked.

**Comment by alps1980** [comment]
Looks like the fix for this issue is causing another defect. When i add customEvents.js file to my application, the connecting lines for pies and their labels disappear. 
This is how the chart looks before adding the file - 
![image](https://cloud.githubusercontent.com/assets/13486501/8879225/bcb21b58-31f5-11e5-894f-29c493ad62b8.png)
And this is how it looks after adding the file - 
![image](https://cloud.githubusercontent.com/assets/13486501/8879253/f2b15bc4-31f5-11e5-85dd-5b4fc31d6ab5.png)
