### ISSUE TITLE
Highstock bar chart drawing issue

### ISSUE THREAD

**Issue by pb61** [blacklabel/custom_events#66]
[BarChartBug.zip](https://github.com/blacklabel/custom_events/files/448000/BarChartBug.zip)

Using customEvents with Highstock JS v4.2.6, any redraw of the bar chart (resize, or toggle series visibility) causes clipping of the left side of the chart. Not including customEvents.js this doesn't occur.

**Comment by sebastianbochan** [comment]
Thank you for reporting. I will check that.

**Comment by Backslider23** [comment]
The problem comes from this line (347)
series.group.clip(series.customClipPath);

If I comment that out, the clipping problem does not show.  That code is only run if the series is not a column or map type.  If I add bar to that list (line 315), and also in the chart redraw (line 365), it is another way to stop the problem.  I am just not sure what I am changing by doing these things.  

We can't have this clipping issue though, so I am looking for any workaround at this point.

**Comment by Backslider23** [comment]
My line numbers are from 1.4.1.  I think they are off by one from version 1.4.2.

**Comment by sebastianbochan** [comment]
I rebuild the custom_events.js core and now all should work properly. If problem will appear, please reopen the case.
